### ISSUE TITLE
pthread.h & Threads issue

### ISSUE THREAD

**Issue by DrewD3V** [mhsjlw/mcpelauncher-mac#4]
When compiling on ElementaryOS, I've gotten an error when running cmake that pthread.h cannot be found. 

**Error:**
-- Looking for pthread.h - not found
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:27 (find_package)

-- Configuring incomplete, errors occurred!

**cmake error:**
Determining if the include file pthread.h exists failed with the following output:
Change Dir:  /home/drew/Downloads/mcpelauncher-mac/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ac1b1/fast"
/usr/bin/make -f CMakeFiles/cmTC_ac1b1.dir/build.make CMakeFiles/cmTC_ac1b1.dir/build
make[1]: Entering directory '/home/drew/Downloads/mcpelauncher-mac/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ac1b1.dir/CheckIncludeFile.c.o
/usr/bin/cc    -m32 -Wl,-U,_BZ2_bzCompress -Wl,-U,_BZ2_bzCompressEnd -Wl,-U,_BZ2_bzCompress -Wl,-U,_BZ2_bzCompressEnd -Wl,-U,_BZ2_bzCompressInit -Wl,-U,_BZ2_bzDecompress -Wl,-U,_BZ2_bzDecompressEnd -Wl,-U,_BZ2_bzDecompressInit -Wno-unused-command-line-argument    -o CMakeFiles/cmTC_ac1b1.dir/CheckIncludeFile.c.o   -c /home/drew/Downloads/mcpelauncher-mac/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
Linking C executable cmTC_ac1b1
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ac1b1.dir/link.txt --verbose=1
/usr/bin/cc   -m32 -Wl,-U,_BZ2_bzCompress -Wl,-U,_BZ2_bzCompressEnd -Wl,-U,_BZ2_bzCompress -Wl,-U,_BZ2_bzCompressEnd -Wl,-U,_BZ2_bzCompressInit -Wl,-U,_BZ2_bzDecompress -Wl,-U,_BZ2_bzDecompressEnd -Wl,-U,_BZ2_bzDecompressInit -Wno-unused-command-line-argument     CMakeFiles/cmTC_ac1b1.dir/CheckIncludeFile.c.o  -o cmTC_ac1b1 -rdynamic 
/usr/bin/ld: cannot find _BZ2_bzCompress: No such file or directory
/usr/bin/ld: cannot find _BZ2_bzCompressEnd: No such file or directory
/usr/bin/ld: cannot find _BZ2_bzCompress: No such file or directory
/usr/bin/ld: cannot find _BZ2_bzCompressEnd: No such file or directory
/usr/bin/ld: cannot find _BZ2_bzCompressInit: No such file or directory
/usr/bin/ld: cannot find _BZ2_bzDecompress: No such file or directory
/usr/bin/ld: cannot find _BZ2_bzDecompressEnd: No such file or directory
/usr/bin/ld: cannot find _BZ2_bzDecompressInit: No such file or directory
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ac1b1.dir/build.make:97: recipe for target 'cmTC_ac1b1' failed
make[1]: *** [cmTC_ac1b1] Error 1
make[1]: Leaving directory '/home/drew/Downloads/mcpelauncher-mac/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ac1b1/fast' failed
make: *** [cmTC_ac1b1/fast] Error 2

**Comment by InusualZ** [comment]
ElementaryOS is not MacOS. Is just an linux distro.

**Comment by MCMrARM** [comment]
You probably want to look at https://github.com/MCMrARM/mcpelauncher-linux instead.

**Comment by DrewD3V** [comment]
Well if you're saying compile the linux version for linux computers, why have the linux instructions in the README? My intentions were to compile this for someone's mac. @MCMrARM

**Comment by DrewD3V** [comment]
@InusualZ Well considering it gives you a notice that it is a linux distro when you are installing it, I figured that one out

**Comment by MCMrARM** [comment]
@DrewD3V we eventually want to merge this upstream to mcpelauncher-linux's repo. Cross compiling is unfortunately not supported.

**Comment by DrewD3V** [comment]
Alright, thanks for clearing that up. @MCMrARM
