### ISSUE TITLE
Followed guide, can't start.

### ISSUE THREAD

**Issue by ili-codes** [mhsjlw/mcpelauncher-mac#5]
When I run `./start_mcpelauncher.sh` I get this error: 
```
loading native libraries
oslib: 2064786064
oslib: libm.dylib: 2597724
loading hybris libraries
loading MCPE
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to find data file: libs/libminecraftpe.so
Signal 6 received
Backtrace elements: 11
#0 0   mcpelauncher                        0x0010c822 _Z12handleSignaliPv + 178
#1 1   libsystem_platform.dylib            0xa18c8e5b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa174ea34 abort + 141
#4 4   libc++abi.dylib                     0xa0333df7 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa0354371 _ZL25default_terminate_handlerv + 244
#6 6   libc++abi.dylib                     0xa0351551 _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa0350f7b _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
#8 8   mcpelauncher                        0x0016380f _ZN10PathHelper12findDataFileERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 8783
#9 9   mcpelauncher                        0x000f55e2 main + 3826
#10 10  libdyld.dylib                       0xa16bf395 start + 1
Dumping stack...
Signal 6 received
./start_mcpelauncher.sh: line 8: 27767 Abort trap: 6           ./build/mcpelauncher
```
How can I go about fixing this?

**Comment by mhsjlw** [comment]
Yeah, getting other reports of this. Can you share the details of your system:
- macOS version
- Device (perhaps year as well)

And let me know:
```
$ ls ~/.local/share/mcpelauncher
```

As well as 

```
$ ls ~/.local/share/mcpelauncher/libs
```

**Comment by ili-codes** [comment]
macOS version: 10.12.6
Device: MacBook Pro Retina (Late 2013), 4gb ram, Intel Iris graphics
`ls: /Users/iliyan/.local/share/mcpelauncher: No such file or directory`
`ls: /Users/iliyan/.local/share/mcpelauncher/libs: No such file or directory`

**Comment by MCMrARM** [comment]
Did you run `./mcpelauncher extract ` + filename?

**Comment by JackNoordhuis** [comment]
I had the same error after installing and then checked the readme which prompted me to run `./setup_bin_libs.sh` before cmake and make which then leads to a warning about CEF not found:
```
CMake Warning at CMakeLists.txt:80 (message):
  CEF not found.  Xbox Live login and APK download features will be disabled.

  To set up CEF please run setup_cef.sh in the source directory.
```
While running the CEF setup script I ran into this error:
```
Scanning dependencies of target libcef_dll_wrapper
make[2]: *** No rule to make target `libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/build'.  Stop.
make[1]: *** [libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/all] Error 2
make: *** [all] Error 2
```

After running the setup_cef.sh script, I ran the cmake command again and the warning disappeared but I run into these errors while compiling:
```
make[2]: *** [gplay_api/CMakeFiles/gplayapi.dir/lib/playapi/util/config.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [gplay_api/CMakeFiles/gplayapi.dir/all] Error 2
make: *** [all] Error 2
```



macOS: 10.13.2
Device: MacBook Pro (15-inch, Late 2011)
Processor: 2.2 GHz Intel Core i7
RAM: 8GB
Graphics:  AMD Radeon HD 6750M 512 MB
                Intel HD Graphics 3000 512 MB


Result of `ls ~/.local/share/mcpelauncher`: `assets`
Result of `ls ~/.local/share/mcpelauncher/libs`: `ls: /Users/Jack/.local/share/mcpelauncher/libs: No such file or directory`

**Comment by MCMrARM** [comment]
CEF is currently not supported

**Comment by MCMrARM** [comment]
You need to get a MCPE x86 apk and use mcpelauncher extract mcpe-apk-path.apk

**Comment by ili-codes** [comment]
I tried to extract the APK but the same error wasn't letting me.

**Comment by MCMrARM** [comment]
Remove libs/cef/ and DO NOT set up CEF.

**Comment by ili-codes** [comment]
I didn't set up CEF, but i was using ./start_mcpelauncher.sh to run extract before, now i use the mcpelauncher in ./builds/ and it works.

**Comment by ili-codes** [comment]
I'll get back on any errors if I have some

**Comment by ili-codes** [comment]
Alright, it works! I can launch MCPE. But, I can't look around with my trackpad. it just glitches out.

**Comment by mhsjlw** [comment]
Known bug. Closing this issue

**Comment by robske110** [comment]
@ili-codes what did you do to fix it? I still got the issue my full install.log: 
https://paste.ee/p/BVnLd

**Comment by MCMrARM** [comment]
For me the mouse issue does not exist and isn't really 'known'. I made mouse smooth, at least for me with https://github.com/mhsjlw/mcpelauncher-mac/commit/2aa5d3b98a861f52976c58badfbbbb127fb076b4

Do you use a laptop touchpad or an external one?

**Comment by robske110** [comment]
@MCMrARM yes, @ili-codes stated that he used a touchpad (trackpad)

**Comment by MCMrARM** [comment]
Well, I tested it on a laptop touchpad and it worked fine, I asked it to know if he uses one of the Apple's external ones.

**Comment by ili-codes** [comment]
@robske110 I used `build/mcpelauncher extract [name].apk`, not `./start_mcpelauncher.sh`

**Comment by ili-codes** [comment]
@MCMrARM I used my internal trackpad. Should I use a mouse instead? I have one to use.

**Comment by InusualZ** [comment]
I think the problem come with the utilization of an VM (Virtual Machine). I have the same problem in my machine using VirtualBox.

**Comment by mhsjlw** [comment]
Ok, figured it out. @MCMrARM doesn't use a Retina display Mac. Because of this, his getRelativeScale is always equal to 1; i.e.: scaling detection is not used and his mouse co-ords are calculated independent of the scale. For machines that use Retina, mouse movements need to be scaled up or down depending to the mouse co-ordinates relative to the framebuffer size. I'll get to fixing this

**Comment by mhsjlw** [comment]
This has been fixed! https://gfycat.com/gifs/detail/PrestigiousTameBadger (digging bug can be seen here as well)
