### ISSUE TITLE
Can you explain it better how to install this im new in mac :)

### ISSUE THREAD

**Issue by ErkamKahriman** [mhsjlw/mcpelauncher-mac#6]

**Comment by mhsjlw** [comment]
Either ask specific questions or refer to the README, it is quite exact

**Comment by ErkamKahriman** [comment]
Yeah i read it already and another question is it working for now i mean is it tested?

**Comment by mhsjlw** [comment]
Yes, most features work. Some stuff is still broken

**Comment by ErkamKahriman** [comment]
I dont know how to install cmake git and openssl on Mac

**Comment by mhsjlw** [comment]
This software might not yet be for you. Once we package it into an app, it will be much easier. I recommend you wait until then

**Comment by MCMrARM** [comment]
As for the most important stuff that do not work are: world saving (aka nothing gets saved) and multiplayer (you can not log in to Xbox Live, but LAN should work otherwise)
