### ISSUE TITLE
On start via ./mcpe_startlauncher.sh

### ISSUE THREAD

**Issue by ErkamKahriman** [mhsjlw/mcpelauncher-mac#7]
```loading native libraries oslib: 2030569248 oslib: libm.dylib: 2954116 loading hybris libraries loading MCPE libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to find data file: libs/libminecraftpe.so Signal 6 received Backtrace elements: 11 #0 0 mcpelauncher 0x00089192 _Z12handleSignaliPv + 178 #1 1 libsystem_platform.dylib 0xa1746e5b _sigtramp + 43 #2 2 ??? 0xffffffff 0x0 + 4294967295 #3 3 libsystem_c.dylib 0xa15cca34 abort + 141 #4 4 libc++abi.dylib 0xa01b1df7 __cxa_bad_cast + 0 #5 5 libc++abi.dylib 0xa01d2371 _ZL25default_terminate_handlerv + 244 #6 6 libc++abi.dylib 0xa01cf551 _ZSt11__terminatePFvvE + 14 #7 7 libc++abi.dylib 0xa01cef7b _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0 #8 8 mcpelauncher 0x000e017f _ZN10PathHelper12findDataFileERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 8783 #9 9 mcpelauncher 0x00071e32 main + 3826 #10 10 libdyld.dylib 0xa153d395 start + 1 Dumping stack... Signal 6 received ./start_mcpelauncher.sh: line 8: 10515 Abort trap: 6 ./build/mcpelauncher $@```

**Comment by mhsjlw** [comment]
> Failed to find data file: libs/libminecraftpe.so
Extract the APK

**Comment by ErkamKahriman** [comment]
I already doed that but i get this error:
![wsbatzg5 jpg large](https://user-images.githubusercontent.com/16340573/35777442-1ca3f68e-09ae-11e8-9b3e-2693db6168f3.jpg)

**Comment by mhsjlw** [comment]
`./setup_bin_libs.sh`

**Comment by ErkamKahriman** [comment]
Does not work..

**Comment by ErkamKahriman** [comment]
Same error at the top

**Comment by mhsjlw** [comment]
You are in the `build/` folder:
```
$ cd ..
$ ./build/mcpelauncher
```

**Comment by ErkamKahriman** [comment]
![pizzanotwork-1](https://user-images.githubusercontent.com/16340573/35809698-c0522680-0a89-11e8-8ffd-d932e8a67b6b.PNG)
Nope

**Comment by mhsjlw** [comment]
Extract your APK. If that doesn't work, you don't have an x86 APK

**Comment by ErkamKahriman** [comment]
...

**Comment by ErkamKahriman** [comment]
Now i get only a Black Screen

**Comment by ErkamKahriman** [comment]
Please HELP
